targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - pokemon.schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: pokemon.schema.graphql
              queries_glob: graphql/fetchpokemons.query.graphql
              output: lib/models/pokemons_query_model.dart